INSERT INTO followships VALUES(DEFAULT, 1, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 1, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 1, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 2, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 2, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 3, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 3, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 4, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 4, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 5, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 5, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 6, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 6, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 7, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 7, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 8, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 8, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 9, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 9, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 10, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 10, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 11, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 11, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 12, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 12, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 13, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 13, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 14, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 14, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 15, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 15, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 16, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 16, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 17, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 17, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 18, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 18, 20, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 20, 19, true, now()::timestamp);
INSERT INTO followships VALUES(DEFAULT, 19, 20, true, now()::timestamp);
INSERT INTO conversations VALUES(DEFAULT, 1, 2);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 1, 3);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 1, 4);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 1, 5);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 1, 6);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 1, 7);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 1, 8);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 1, 9);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 1, 10);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 1, 11);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 2, 1);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 2, 3);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 2, 4);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 2, 5);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 2, 6);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 2, 7);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 2, 8);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 2, 9);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 2, 10);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 2, 11);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 3, 1);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 3, 2);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 3, 4);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 3, 5);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 3, 6);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 3, 7);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 3, 8);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 3, 9);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 3, 10);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 3, 11);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 4, 1);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 4, 2);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 4, 3);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 4, 5);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 4, 6);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 4, 7);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 4, 8);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 4, 9);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 4, 10);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 4, 11);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 5, 1);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 5, 2);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 5, 3);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 5, 4);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 5, 6);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 5, 7);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 5, 8);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 5, 9);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 5, 10);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 5, 11);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 6, 1);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 6, 2);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 6, 3);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 6, 4);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 6, 5);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 6, 7);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 6, 8);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 6, 9);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 6, 10);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 6, 11);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 7, 1);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 7, 2);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 7, 3);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 7, 4);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 7, 5);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 7, 6);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 7, 8);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 7, 9);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 7, 10);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 7, 11);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 8, 1);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 8, 2);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 8, 3);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 8, 4);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 8, 5);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 8, 6);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 8, 7);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 8, 9);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 8, 10);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 8, 11);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 9, 1);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 9, 2);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 9, 3);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 9, 4);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 9, 5);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 9, 6);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 9, 7);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 9, 8);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 9, 10);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 9, 11);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 10, 1);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 10, 2);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 10, 3);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 10, 4);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 10, 5);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 10, 6);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 10, 7);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 10, 8);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 10, 9);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 10, 11);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 11, 1);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 1, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 11, 2);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 2, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 11, 3);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 3, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 11, 4);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 4, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 11, 5);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 5, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 11, 6);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 6, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 11, 7);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 7, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 11, 8);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 8, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 11, 9);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 9, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO conversations VALUES(DEFAULT, 11, 10);
INSERT INTO direct_messages VALUES(DEFAULT, 11, 10, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 11, 'Hello', NULL, true, CURRVAL(pg_get_serial_sequence('conversations','id')), CURRENT_TIMESTAMP);
