--Creating followships to send messages
INSERT INTO fellowships VALUES(DEFAULT, 1, 2, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 2, 1, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 1, 3, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 3, 1, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 1, 4, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 4, 1, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 1, 5, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 5, 1, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 1, 6, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 6, 1, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 1, 7, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 7, 1, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 1, 8, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 8, 1, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 1, 9, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 9, 1, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 1, 10, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 10, 1, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 2, 3, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 3, 2, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 2, 4, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 4, 2, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 2, 5, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 5, 2, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 2, 6, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 6, 2, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 2, 7, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 7, 2, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 2, 8, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 8, 2, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 2, 9, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 9, 2, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 2, 10, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 10, 2, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 3, 4, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 4, 3, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 3, 5, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 5, 3, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 3, 6, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 6, 3, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 3, 7, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 7, 3, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 3, 8, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 8, 3, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 3, 9, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 9, 3, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 3, 10, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 10, 3, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 4, 5, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 5, 4, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 4, 6, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 6, 4, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 4, 7, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 7, 4, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 4, 8, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 8, 4, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 4, 9, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 9, 4, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 4, 10, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 10, 4, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 5, 6, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 6, 5, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 5, 7, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 7, 5, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 5, 8, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 8, 5, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 5, 9, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 9, 5, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 5, 10, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 10, 5, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 6, 7, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 7, 6, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 6, 8, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 8, 6, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 6, 9, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 9, 6, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 6, 10, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 10, 6, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 7, 8, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 8, 7, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 7, 9, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 9, 7, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 7, 10, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 10, 7, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 8, 9, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 9, 8, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 8, 10, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 10, 8, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 9, 10, true, CURRENT_TIMESTAMP);
INSERT INTO fellowships VALUES(DEFAULT, 10, 9, true, CURRENT_TIMESTAMP);

--Creating conversations for messages
INSERT INTO conversations VALUES(DEFAULT, 1, 2);
INSERT INTO conversations VALUES(DEFAULT, 2, 1);
INSERT INTO conversations VALUES(DEFAULT, 1, 3);
INSERT INTO conversations VALUES(DEFAULT, 3, 1);
INSERT INTO conversations VALUES(DEFAULT, 1, 4);
INSERT INTO conversations VALUES(DEFAULT, 4, 1);
INSERT INTO conversations VALUES(DEFAULT, 1, 5);
INSERT INTO conversations VALUES(DEFAULT, 5, 1);
INSERT INTO conversations VALUES(DEFAULT, 1, 6);
INSERT INTO conversations VALUES(DEFAULT, 6, 1);
INSERT INTO conversations VALUES(DEFAULT, 1, 7);
INSERT INTO conversations VALUES(DEFAULT, 7, 1);
INSERT INTO conversations VALUES(DEFAULT, 1, 8);
INSERT INTO conversations VALUES(DEFAULT, 8, 1);
INSERT INTO conversations VALUES(DEFAULT, 1, 9);
INSERT INTO conversations VALUES(DEFAULT, 9, 1);
INSERT INTO conversations VALUES(DEFAULT, 1, 10);
INSERT INTO conversations VALUES(DEFAULT, 10, 1);
INSERT INTO conversations VALUES(DEFAULT, 2, 3);
INSERT INTO conversations VALUES(DEFAULT, 3, 2);
INSERT INTO conversations VALUES(DEFAULT, 2, 4);
INSERT INTO conversations VALUES(DEFAULT, 4, 2);
INSERT INTO conversations VALUES(DEFAULT, 2, 5);
INSERT INTO conversations VALUES(DEFAULT, 5, 2);
INSERT INTO conversations VALUES(DEFAULT, 2, 6);
INSERT INTO conversations VALUES(DEFAULT, 6, 2);
INSERT INTO conversations VALUES(DEFAULT, 2, 7);
INSERT INTO conversations VALUES(DEFAULT, 7, 2);
INSERT INTO conversations VALUES(DEFAULT, 2, 8);
INSERT INTO conversations VALUES(DEFAULT, 8, 2);
INSERT INTO conversations VALUES(DEFAULT, 2, 9);
INSERT INTO conversations VALUES(DEFAULT, 9, 2);
INSERT INTO conversations VALUES(DEFAULT, 2, 10);
INSERT INTO conversations VALUES(DEFAULT, 10, 2);
INSERT INTO conversations VALUES(DEFAULT, 3, 4);
INSERT INTO conversations VALUES(DEFAULT, 4, 3);
INSERT INTO conversations VALUES(DEFAULT, 3, 5);
INSERT INTO conversations VALUES(DEFAULT, 5, 3);
INSERT INTO conversations VALUES(DEFAULT, 3, 6);
INSERT INTO conversations VALUES(DEFAULT, 6, 3);
INSERT INTO conversations VALUES(DEFAULT, 3, 7);
INSERT INTO conversations VALUES(DEFAULT, 7, 3);
INSERT INTO conversations VALUES(DEFAULT, 3, 8);
INSERT INTO conversations VALUES(DEFAULT, 8, 3);
INSERT INTO conversations VALUES(DEFAULT, 3, 9);
INSERT INTO conversations VALUES(DEFAULT, 9, 3);
INSERT INTO conversations VALUES(DEFAULT, 3, 10);
INSERT INTO conversations VALUES(DEFAULT, 10, 3);
INSERT INTO conversations VALUES(DEFAULT, 4, 5);
INSERT INTO conversations VALUES(DEFAULT, 5, 4);
INSERT INTO conversations VALUES(DEFAULT, 4, 6);
INSERT INTO conversations VALUES(DEFAULT, 6, 4);
INSERT INTO conversations VALUES(DEFAULT, 4, 7);
INSERT INTO conversations VALUES(DEFAULT, 7, 4);
INSERT INTO conversations VALUES(DEFAULT, 4, 8);
INSERT INTO conversations VALUES(DEFAULT, 8, 4);
INSERT INTO conversations VALUES(DEFAULT, 4, 9);
INSERT INTO conversations VALUES(DEFAULT, 9, 4);
INSERT INTO conversations VALUES(DEFAULT, 4, 10);
INSERT INTO conversations VALUES(DEFAULT, 10, 4);
INSERT INTO conversations VALUES(DEFAULT, 5, 6);
INSERT INTO conversations VALUES(DEFAULT, 6, 5);
INSERT INTO conversations VALUES(DEFAULT, 5, 7);
INSERT INTO conversations VALUES(DEFAULT, 7, 5);
INSERT INTO conversations VALUES(DEFAULT, 5, 8);
INSERT INTO conversations VALUES(DEFAULT, 8, 5);
INSERT INTO conversations VALUES(DEFAULT, 5, 9);
INSERT INTO conversations VALUES(DEFAULT, 9, 5);
INSERT INTO conversations VALUES(DEFAULT, 5, 10);
INSERT INTO conversations VALUES(DEFAULT, 10, 5);
INSERT INTO conversations VALUES(DEFAULT, 6, 7);
INSERT INTO conversations VALUES(DEFAULT, 7, 6);
INSERT INTO conversations VALUES(DEFAULT, 6, 8);
INSERT INTO conversations VALUES(DEFAULT, 8, 6);
INSERT INTO conversations VALUES(DEFAULT, 6, 9);
INSERT INTO conversations VALUES(DEFAULT, 9, 6);
INSERT INTO conversations VALUES(DEFAULT, 6, 10);
INSERT INTO conversations VALUES(DEFAULT, 10, 6);
INSERT INTO conversations VALUES(DEFAULT, 7, 8);
INSERT INTO conversations VALUES(DEFAULT, 8, 7);
INSERT INTO conversations VALUES(DEFAULT, 7, 9);
INSERT INTO conversations VALUES(DEFAULT, 9, 7);
INSERT INTO conversations VALUES(DEFAULT, 7, 10);
INSERT INTO conversations VALUES(DEFAULT, 10, 7);
INSERT INTO conversations VALUES(DEFAULT, 8, 9);
INSERT INTO conversations VALUES(DEFAULT, 9, 8);
INSERT INTO conversations VALUES(DEFAULT, 8, 10);
INSERT INTO conversations VALUES(DEFAULT, 10, 8);
INSERT INTO conversations VALUES(DEFAULT, 9, 10);
INSERT INTO conversations VALUES(DEFAULT, 10, 9);

--Creating messages
INSERT INTO direct_messages VALUES(DEFAULT, 1, 2, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 1, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 3, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 1, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 4, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 1, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 5, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 1, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 6, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 1, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 7, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 1, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 8, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 1, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 9, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 1, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 1, 10, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 1, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 3, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 2, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 4, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 2, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 5, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 2, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 6, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 2, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 7, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 2, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 8, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 2, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 9, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 2, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 2, 10, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 2, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 4, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 3, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 5, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 3, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 6, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 3, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 7, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 3, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 8, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 3, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 9, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 3, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 3, 10, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 3, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 5, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 4, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 6, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 4, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 7, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 4, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 8, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 4, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 9, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 4, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 4, 10, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 4, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 6, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 5, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 7, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 5, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 8, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 5, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 9, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 5, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 5, 10, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 5, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 7, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 6, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 8, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 6, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 9, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 6, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 6, 10, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 6, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 8, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 7, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 9, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 7, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 7, 10, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 7, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 9, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 8, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 8, 10, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 8, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 9, 10, 'Hello', NULL, true,);
INSERT INTO direct_messages VALUES(DEFAULT, 10, 9, 'Hello', NULL, true,);
