INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 0),
       (SELECT id FROM users LIMIT 1 OFFSET 0),
       (SELECT id FROM users LIMIT 1 OFFSET 1), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 1),
       (SELECT id FROM users LIMIT 1 OFFSET 1),
       (SELECT id FROM users LIMIT 1 OFFSET 2), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 2),
       (SELECT id FROM users LIMIT 1 OFFSET 2),
       (SELECT id FROM users LIMIT 1 OFFSET 3), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 3),
       (SELECT id FROM users LIMIT 1 OFFSET 3),
       (SELECT id FROM users LIMIT 1 OFFSET 4), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 4),
       (SELECT id FROM users LIMIT 1 OFFSET 4),
       (SELECT id FROM users LIMIT 1 OFFSET 5), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 5),
       (SELECT id FROM users LIMIT 1 OFFSET 5),
       (SELECT id FROM users LIMIT 1 OFFSET 6), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 6),
       (SELECT id FROM users LIMIT 1 OFFSET 6),
       (SELECT id FROM users LIMIT 1 OFFSET 7), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 7),
       (SELECT id FROM users LIMIT 1 OFFSET 7),
       (SELECT id FROM users LIMIT 1 OFFSET 8), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 8),
       (SELECT id FROM users LIMIT 1 OFFSET 8),
       (SELECT id FROM users LIMIT 1 OFFSET 9), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 9),
       (SELECT id FROM users LIMIT 1 OFFSET 9),
       (SELECT id FROM users LIMIT 1 OFFSET 10), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 10),
       (SELECT id FROM users LIMIT 1 OFFSET 10),
       (SELECT id FROM users LIMIT 1 OFFSET 11), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 11),
       (SELECT id FROM users LIMIT 1 OFFSET 11),
       (SELECT id FROM users LIMIT 1 OFFSET 12), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 12),
       (SELECT id FROM users LIMIT 1 OFFSET 12),
       (SELECT id FROM users LIMIT 1 OFFSET 13), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 13),
       (SELECT id FROM users LIMIT 1 OFFSET 13),
       (SELECT id FROM users LIMIT 1 OFFSET 14), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 14),
       (SELECT id FROM users LIMIT 1 OFFSET 14),
       (SELECT id FROM users LIMIT 1 OFFSET 15), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 15),
       (SELECT id FROM users LIMIT 1 OFFSET 15),
       (SELECT id FROM users LIMIT 1 OFFSET 16), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 16),
       (SELECT id FROM users LIMIT 1 OFFSET 16),
       (SELECT id FROM users LIMIT 1 OFFSET 17), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 17),
       (SELECT id FROM users LIMIT 1 OFFSET 17),
       (SELECT id FROM users LIMIT 1 OFFSET 18), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 18),
       (SELECT id FROM users LIMIT 1 OFFSET 18),
       (SELECT id FROM users LIMIT 1 OFFSET 19), CURRENT_TIMESTAMP);
INSERT INTO retweets
VALUES (DEFAULT, (SELECT id FROM tweets LIMIT 1 OFFSET 19),
       (SELECT id FROM users LIMIT 1 OFFSET 19),
       (SELECT id FROM users LIMIT 1 OFFSET 20), CURRENT_TIMESTAMP);
