INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 20, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 19, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 9, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 16, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 12, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 6, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 13, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 8, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 1, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 18, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 17, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 15, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 2, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 14, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 5, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 4, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 10, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 7, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
INSERT INTO tweets
VALUES (DEFAULT, 'HELLO', 3, CURRENT_TIMESTAMP, NULL);
